### ISSUE TITLE
error: -db_soft_mask 40

### ISSUE THREAD

**Issue by MontseTor** [ikmb-denbi/genome-annotation#4]
Process: makeblastdb

"Error: [makeblastdb] No sequences matched any of the masks provided.
Please ensure that the -parse_seqids option is used in the filtering program as well as makeblastdb. "

Consequently the files .naa, .nab, .nac are not created.

Might be an issue with the version of blast+ used by repeatmasker

**Comment by marchoeppner** [comment]
Looks valid and is likely related to the outdated blast+ version that is bundled with RM. To maintain conda compatibility, we should remove the rm masking.

**Comment by marchoeppner** [comment]
No available workaround; rm masking blast databases has therefore been removed.
