### ISSUE TITLE
Fully check singularity support

### ISSUE THREAD

**Issue by MontseTor** [ikmb-denbi/genome-annotation#7]
We are having an issue where the scripts in /bin are not properly picked up for some reason when running in singularity

**Comment by marchoeppner** [comment]
This should work now; remaining issues are probably due to misconfigured singularity setups on specific systems. Runs through fine on two test installations. https://github.com/ikmb-denbi/genome-annotation/commit/dd769f051ee47429ef73829c78d08a4c056d7c44
